version: '3.8'

services:
  web:
    build: ./Server
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=mssql+pyodbc://sa:Badr1234!@db:1433/master?driver=ODBC+Driver+17+for+SQL+Server
    volumes:
      - ./Server/app:/code/app
      - ./Datasets:/data 
    networks:
      - my_network
    command: >
      sh -c "
      python3 /code/app/load_dataset.py &&
      echo 'Dataset loaded, starting FastAPI...';
      uvicorn app.main:app --host 0.0.0.0 --port 8000"

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Badr1234!
      - MSSQL_USER=sa
      - MSSQL_DATABASE=master
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - my_network



volumes:
  mssql_data:

networks:
  my_network:
    driver: bridge
