version: '3.8'

services:
  web:
    build: ./Server
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./Server/app:/code/app
      - ./Data:/data 
    networks:
      - my_network
    command: >
      sh -c "
      python3 /code/app/load_dataset.py &&
      echo 'Dataset loaded, starting FastAPI...';
      uvicorn app.main:app --host 0.0.0.0 --port 8000"

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}
      - MSSQL_USER=${DB_USER}
      - MSSQL_DATABASE=${DB_NAME}
    volumes:
      - mssql_data:/var/opt/mssql
      - ./Data:/shared_data
    networks:
      - my_network



  frontend:
    build: ./Client
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://web:8000  
    volumes:
      - ./Client:/app
    networks:
      - my_network
    depends_on:
      - web
    command: bash -c "npm install && npm run build && npm start"  
volumes:
  mssql_data:

networks:
  my_network:
    driver: bridge
